### ISSUE TITLE
 Run failed: gen-site - master

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum.github.io#7]
For a while we are getting these messages from Github: Building and deploying website: Some jobs were not successful

@HenkKalkwater, would you mind to take a look? Example https://github.com/sailfishos-chum/sailfishos-chum.github.io/actions/runs/7676137078

**Comment by HenkKalkwater** [comment]
For some reasons I do not get notifications from failed workflows, perhaps since workflows triggered from the schedule are attached to your user account? I can't find any settings to change that, however.

By the way, it should be fixed now. It only happened under the specific condition that an app with a Markdown description would be recently updated, which is why I probably did not catch it before.

_PS: I should have noticed it earlier that there had been a lack of app updates in my RSS reader, I found it suspiciously inactively lately :)_

**Comment by rinigus** [comment]
No problem, I will then open an issue if it happens again. :)
